title: Tony Cruise
description: This site provides support materials for the various books and tools that I have published directly or as Electric Adventures
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
