title: Tony Cruise (aka Electric Adventures)
description: This site provides support materials for the various books and tools that I have published
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
